AWSTemplateFormatVersion: '2010-09-09'
Description: Create a single EC2 instance

Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.micro
      ImageId: ami-00f34bf9aeacdf007